### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by paskal**
Hey, thanks for the script. These are fixes for small typos.

### CODE REVIEW

**Comment by selivan** [comment]
Thanks for the contribution :+1:

**Comment by paskal** [comment]
@selivan btw do you mind adding port 443 as a default one? Doesn't make sense for me to add it each time, nobody uses non-standard ports for HTTPS.

**Comment by selivan** [comment]
Makes sense. Here: 6db203f371dd83f11181f2cd170d12bee5f6d998

**Comment by paskal** [comment]
Thanks a lot!

**Pull request merged**
